name: Terraform EC2 via OIDC (No Secrets in GitHub)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Choose apply or destroy"
        type: choice
        options:
          - apply
          - destroy
        default: apply
      environment:
        type: string
        default: dev
      region:
        type: string
        default: eu-west-1
      program:
        type: string
        default: datalake
      account_id:
        type: string
        default: "483416847573"

  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_environment: ${{ inputs.environment || 'dev' }}
      TF_VAR_region:      ${{ inputs.region || 'eu-west-1' }}
      TF_VAR_program:     ${{ inputs.program || 'datalake' }}
      TF_VAR_account_id:  ${{ inputs.account_id || '483416847573' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC (no secrets)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::483416847573:role/firstroleinoidc
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: ${{ inputs.mode == 'apply' }}
        run: terraform plan -input=false -no-color -out=tfplan.bin

      - name: Terraform Apply (auto-approve for demo)
        if: ${{ inputs.mode == 'apply' && github.ref == 'refs/heads/main' }}
        run: terraform apply -auto-approve -input=false tfplan.bin

      - name: Terraform Destroy (auto-approve)
        if: ${{ inputs.mode == 'destroy' }}
        run: terraform destroy -auto-approve -input=false
